### ISSUE TITLE
Implement UI/UX for MyPage feature.

### ISSUE THREAD

**Issue by vanltt** [prdlab/telegram-ios#10]

**Comment by vanltt** [comment]
Feedbacks : 
1 - Language selection : Sort Language list by Name.
2 - Add new Work :  "from"/"to" should be selected from datetimepicker then convert to string.
3 - Number of project : keyboard should be number keyboard.

**Comment by hungtranprd88** [comment]
@vanltt : Done

**Comment by vanltt** [comment]
This issue was moved to prdlab/wrappy-ios#10
