### ISSUE TITLE
Implement KYC feature

### ISSUE THREAD

**Issue by vanltt** [prdlab/telegram-ios#15]

**Comment by vanltt** [comment]
Requirement:
1. Private info (see PRD_Wrappy_FunctionsDiagram.pdf).
2. Note: "FaceImage" is uploaded to Firebase-Storage and save link in Firebase Database.

**Comment by vanltt** [comment]
* Note : 
- "FaceImage" file name convention is : "[timestamp of current time]_[userID]".jpg

**Comment by vanltt** [comment]
Feedback:
- Delete "FaceImage" doesn't work.

**Comment by hungtranprd88** [comment]
@vanltt : Done

**Comment by vanltt** [comment]
This issue was moved to prdlab/wrappy-ios#15
