### ISSUE TITLE
Update MyPage feature.

### ISSUE THREAD

**Issue by vanltt** [prdlab/telegram-ios#16]
1. Change Language to Language list, allow user add more language to Language list.
2. Add Level attribute for language.
3. Remove these info below: Full name, sex, year of birth, city, country, phone number, email.
4. Add new info: Education list, Favorite list, Hobby list.

**Comment by hungtranprd88** [comment]
Done

**Comment by vanltt** [comment]
This issue was moved to prdlab/wrappy-ios#16
