### ISSUE TITLE
add wrappy-emoicons

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/telegram-ios#4]
Plz add emoicons packages in here (https://drive.google.com/drive/folders/0B0ZAdTExVnPbN0N4OVU2VVk3U3M) to app
set each emoicon package to different category
- wrappy name-1 `Option_1`, package-name is same as folder-name.
- wrappy name-1 `Option_2`, package-name is same as folder-name.
- wrappy name-1 `Option_3`, package-name is same as folder-name.

■ target-branch= **poc1**

**Comment by vanltt** [comment]
This issue was moved to prdlab/wrappy-ios#4
